[package]
name = "generate-tests-from-json"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "*"
proc-macro2 = "*"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
